package com.dzakdzaks.movies.util;

import com.dzakdzaks.movieLocals.BuildConfig;
import com.dzakdzaks.movies.data.remote.response.movie.Movie;
import com.dzakdzaks.movies.data.remote.response.tvshow.TvShow;

import java.util.ArrayList;

public class FakeDummy {

    public static ArrayList<Movie> generateMovie() {
        ArrayList<Movie> movies = new ArrayList<>();

        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        movies.add(new Movie(384018,
                "Fast & Furious Presents: Hobbs & Shaw",
                "Fast & Furious Presents: Hobbs & Shaw",
                "en",
                "A spinoff of The Fate of the Furious, focusing on Johnson's US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Statham's Deckard Shaw.",
                "2019-08-01",
                BuildConfig.BASE_URL_IMG + "/keym7MPn1icW1wWfzMnW3HeuzWU.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/hpgda6P9GutvdkDX5MUJ92QG9aj.jpg",
                9));
        return movies;
    }

    public static ArrayList<TvShow> generateTvShow() {
        ArrayList<TvShow> tvShows = new ArrayList<>();

        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        tvShows.add(new TvShow(100,
                "I Am Not an Animal",
                "I Am Not an Animal",
                "en",
                "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
                "2004-05-10",
                BuildConfig.BASE_URL_IMG + "/nMhv6jG5dtLdW7rgguYWvpbk0YN.jpg",
                BuildConfig.BASE_URL_IMG_LANDSCAPE + "/ok1YiumqOCYzUmuTktnupOQOvV5.jpg",
                9.5));
        return tvShows;
    }
}
